### ISSUE TITLE
Installation fails with invalid resource apt-source

### ISSUE THREAD

**Issue by ip512** [simodima/vagrant-rabbitmq#1]
I get an error with vagrant 1.5.3 / VirtualBox 4.3.10 on Mac OS.
Here is the complete error trace : 
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise32'...
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: symfonyday-rome-mq
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 5672 => 8672 (adapter 1)
    default: 15672 => 18672 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 4.3
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => /Users/gpelletier/workspace/rabbitmq/vagrant-rabbitmq
    default: /tmp/vagrant-puppet-1/manifests => /Users/gpelletier/workspace/rabbitmq/vagrant-rabbitmq/puppet/manifests
    default: /tmp/vagrant-puppet-1/modules-0 => /Users/gpelletier/workspace/rabbitmq/vagrant-rabbitmq/puppet/modules
==> default: Running provisioner: puppet...
Running Puppet with default.pp...
stdin: is not a tty
warning: Could not retrieve fact fqdn
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apt::source at /tmp/vagrant-puppet-1/manifests/default.pp:8 on node symfonyday-rome-mq
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet apply --modulepath '/tmp/vagrant-puppet-1/modules-0:/etc/puppet/modules' --color=false --manifestdir /tmp/vagrant-puppet-1/manifests --detailed-exitcodes /tmp/vagrant-puppet-1/manifests/default.pp || [ $? -eq 2 ]

Stdout from the command:

warning: Could not retrieve fact fqdn

Stderr from the command:

stdin: is not a tty
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apt::source at /tmp/vagrant-puppet-1/manifests/default.pp:8 on node symfonyday-rome-mq

**Comment by rjvitorino** [comment]
+1

**Comment by rjvitorino** [comment]
@ip512 did you manage to find a solution to this?

**Comment by ip512** [comment]
Hi @rjfv 
I used the following bootstrap.sh script to install rabbitmq on a vm:

```
#!/usr/bin/env bash

cat >> /etc/apt/sources.list <<EOT
deb http://www.rabbitmq.com/debian/ testing main
EOT

wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
apt-key add rabbitmq-signing-key-public.asc

apt-get update
apt-get install -q -y screen htop vim curl wget
apt-get install -q -y rabbitmq-server

rabbitmqctl add_user ip512 mysecretpassword
rabbitmqctl set_user_tags ip512 administrator
rabbitmqctl set_permissions ip512 ".*" ".*" ".*"

# RabbitMQ Plugins
service rabbitmq-server stop
rabbitmq-plugins enable rabbitmq_management
#rabbitmq-plugins enable rabbitmq_jsonrpc
#rabbitmq-plugins enable rabbitmq_federation
#rabbitmq-plugins enable rabbitmq_federation_management
service rabbitmq-server start
```

at the end, for my purposes it's more simple than using puppet or chef

**Comment by rjvitorino** [comment]
@ip512  thanks a lot!

**Comment by alexbeletsky** [comment]
+1,

``` bash
==> default: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class rabbitmq::server at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/default.pp:12 on node symfonyday-rome-mq.localdomain
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by alexbeletsky** [comment]
@ip512 thanks a lot, works as charm.

**Comment by soniCaH** [comment]
Same error as @alexbeletsky 
- removing all puppetry and using the bootstrap.sh works! 

Thanks @ip512
